import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopRail from "@/components/dashboard/TopRail";
import TimerStrip from "@/components/dashboard/TimerStrip";
import CaptureBox from "@/components/dashboard/CaptureBox";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Brendan OS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col antialiased">
        <TopRail />
        <TimerStrip />
        <main className="mx-auto max-w-6xl p-6">{children}</main>
        <CaptureBox />
      </body>
    </html>
  );
}
