import type { Metadata } from "next";
import { Archivo, Inter_Tight } from "next/font/google";
import TopRail from "@/components/dashboard/TopRail";
import CaptureBox from "@/components/dashboard/CaptureBox";
import "./globals.css";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["500", "600", "700", "800"],
});

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Brendan OS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${interTight.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col antialiased">
        <TopRail />
        {/* w-full is load-bearing here, not decorative: body is a flex
            column, and auto margins on a flex item disable cross-axis
            stretch — without an explicit width, <main> sizes to its
            content's max-content width instead of the viewport, letting
            any sufficiently wide descendant (e.g. a table needing to
            scroll internally) inflate the whole page's width instead of
            scrolling in place.

            No max-width/padding here on purpose (removed 2026-08-27): each
            page's own board component already sets its own `maxWidth` and
            padding (Reflections/Ideas/Media all use 1220px, Tasks now wants
            2200px) — a shared cap here was silently clipping all of them
            down to 1152px regardless of what they actually asked for. */}
        <main className="w-full">{children}</main>
        <CaptureBox />
      </body>
    </html>
  );
}
